function write_params_in_ver2(p)
%WRITE_PARAMS_IN_VER2 Write `params_ver2.in` in the format expected by `rc_ver2.f`.
%
% The Fortran code reads a simple sequence of values (with some blank
% separator lines) from `params_ver2.in`. This function takes the parameter
% cell array produced by `get_parameters_ver2()` and writes the file in the
% correct order.

if nargin ~= 1
    error('write_params_in_ver2 requires a single cell array argument');
end

if ~iscell(p) || numel(p) < 42
    error('Expected parameter cell array with at least 42 entries');
end

fid = fopen('params_ver2.in','w');
if fid < 0
    error('Failed to open params_ver2.in for writing');
end

cleanupObj = onCleanup(@() fclose(fid));

% Header: rc_ver2.f skips first 3 records.
fprintf(fid,'generated by write_params_in_ver2\n\n\n');

% --- Integration control ---
fprintf(fid,'%s\n', num2str(p{1}));  % RESTART (y/n)
fprintf(fid,'%s\n', num2str(p{2}));  % ENDTIME (days)
fprintf(fid,'%s\n', num2str(p{3}));  % DT (minutes)
fprintf(fid,'%s\n', num2str(p{4}));  % AVTIME (days)
fprintf(fid,'%s\n', num2str(p{5}));  % PRINFREQ (hours)
fprintf(fid,'\n\n');

% --- Radiation / calendar / albedo ---
fprintf(fid,'%s\n', num2str(p{6}));   % RADINT (interactive radiation)
fprintf(fid,'%s\n', num2str(p{7}));   % ICLDS (interactive clouds)
fprintf(fid,'%s\n', num2str(p{8}));   % TSINT (interactive surface temp)
fprintf(fid,'%s\n', num2str(p{9}));   % RADFREQ (hours)
fprintf(fid,'%s\n', num2str(p{10}));  % SCON (solar constant)
fprintf(fid,'%s\n', num2str(p{11}));  % RLAT (deg)
fprintf(fid,'%s\n', num2str(p{12}));  % MONTH
fprintf(fid,'%s\n', num2str(p{13}));  % IDAY
fprintf(fid,'%s\n', num2str(p{14}));  % HOUR
fprintf(fid,'%s\n', num2str(p{15}));  % TDEP (time-dependent radiation)
fprintf(fid,'%s\n', num2str(p{16}));  % DDEP (date-dependent radiation)
fprintf(fid,'%s\n', num2str(p{17}));  % DARAD (diurnal-average radiation)
fprintf(fid,'%s\n', num2str(p{18}));  % ANRAD (annual-average radiation)
fprintf(fid,'%s\n', num2str(p{19}));  % CALB (calculate ocean albedo)
fprintf(fid,'%s\n', num2str(p{20}));  % ALB (fixed albedo)
fprintf(fid,'\n\n');

% --- Well-mixed greenhouse gases + multipliers ---
fprintf(fid,'%s\n', num2str(p{21}));  % CO2
fprintf(fid,'%s\n', num2str(p{22}));  % CH4
fprintf(fid,'%s\n', num2str(p{23}));  % N2O
fprintf(fid,'%s\n', num2str(p{24}));  % CFC11
fprintf(fid,'%s\n', num2str(p{25}));  % CFC12
fprintf(fid,'%s\n', num2str(p{26}));  % H2OI (interactive water vapor)
fprintf(fid,'%s\n', num2str(p{27}));  % H2OM (H2O multiplier to radiation)
fprintf(fid,'%s\n', num2str(p{28}));  % O3M (O3 multiplier to radiation)
fprintf(fid,'\n\n');

% --- Convection switches ---
fprintf(fid,'%s\n', num2str(p{29}));  % DCONV (dry adjustment)
fprintf(fid,'%s\n', num2str(p{30}));  % MCONV (moist convection)
fprintf(fid,'\n\n');

% --- Surface fluxes / slab ocean-land ---
fprintf(fid,'%s\n', num2str(p{31}));  % FLUXSWITCH (turbulent fluxes)
fprintf(fid,'%s\n', num2str(p{32}));  % BETA (fraction surface water)
fprintf(fid,'%s\n', num2str(p{33}));  % DEPTH (mixed layer depth, m)
fprintf(fid,'%s\n', num2str(p{34}));  % VS0 (surface wind speed, m/s)

% The Fortran code expects two separator records before WCUBE.
fprintf(fid,'\n\n');

% --- Background omega profile ---
fprintf(fid,'%s\n', num2str(p{35}));  % WCUBE (cubic omega profile?)
fprintf(fid,'%s\n', num2str(p{36}));  % WMAX (extreme omega)
fprintf(fid,'%s\n', num2str(p{37}));  % PERIOD (days)
fprintf(fid,'%s\n', num2str(p{38}));  % PWZERO (top zero, mb)
fprintf(fid,'%s\n', num2str(p{39}));  % PWBOTTOM (bottom zero, mb)
fprintf(fid,'%s\n', num2str(p{40}));  % PWMAX (peak pressure, mb)
fprintf(fid,'\n\n');

% --- Weak temperature gradient ---
fprintf(fid,'%s\n', num2str(p{41}));  % WTG (y/n)
fprintf(fid,'%s\n', num2str(p{42}));  % PFIX (mb)