#!/usr/bin/env python3
"""
Convert params_ver2_table.in (table format) to params_ver2.in (value-only format for rc_ver2.f).

Input format: same as params_ver2_table.txt (Parameter, Value, Units, Description columns).
Output: params_ver2.in with one value per line and blank separators as expected by Fortran.

Usage:
  python table_to_params.py [INPUT_TABLE [OUTPUT_PARAMS]]
  python table_to_params.py params_ver2_table.in params_ver2.in
  Defaults: params_ver2_table.in -> params_ver2.in
"""

from __future__ import annotations

import sys
from pathlib import Path

# Parameter names in the order they appear in params_ver2.in (value lines only).
PARAM_NAMES = [
    "RESTART", "ENDTIME", "DT", "AVTIME", "PRINFREQ",
    "RADINT", "ICLDS", "TSINT", "RADFREQ", "SCON", "RLAT", "MONTH", "IDAY", "HOUR",
    "TDEP", "DDEP", "DARAD", "ANRAD", "CALB", "ALB",
    "CO2", "CH4", "N2O", "CFC11", "CFC12", "H2OI", "H2OM", "O3M",
    "DCONV", "MCONV",
    "FLUXSWITCH", "BETA", "DEPTH", "VS0",
    "WCUBE", "WMAX", "PERIOD", "PWZERO", "PWBOTTOM", "PWMAX",
    "WTG", "PFIX",
]

# 1-based line numbers in params_ver2.in that hold a value (same as in write_params_described.py).
VALUE_LINE_NUMBERS = [
    4, 5, 6, 7, 8,
    11, 12, 13, 14, 15, 16, 17, 18, 19,
    20, 21, 22, 23, 24, 25,
    28, 29, 30, 31, 32, 33, 34, 35,
    38, 39,
    42, 43, 44, 45,
    48, 49, 50, 51, 52, 53,
    56, 57,
]

# Total lines in params_ver2.in (header + blanks + value lines).
TOTAL_LINES = 59


def parse_table(table_path: Path) -> dict[str, str]:
    """Read table file; return dict param_name -> value (string)."""
    text = table_path.read_text()
    lines = text.splitlines()
    param_to_value: dict[str, str] = {}
    for line in lines:
        line = line.strip()
        if not line or line.startswith("-") or line.lower().startswith("parameter"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            name, value = parts[0], parts[1]
            if name in PARAM_NAMES:
                param_to_value[name] = value
    return param_to_value


def build_params_lines(param_to_value: dict[str, str]) -> list[str]:
    """Build the 59 lines of params_ver2.in."""
    if len(PARAM_NAMES) != len(VALUE_LINE_NUMBERS):
        raise RuntimeError("PARAM_NAMES and VALUE_LINE_NUMBERS length mismatch")
    value_line_set = set(VALUE_LINE_NUMBERS)
    values_by_line: dict[int, str] = {}
    for idx, name in enumerate(PARAM_NAMES):
        line_num = VALUE_LINE_NUMBERS[idx]
        values_by_line[line_num] = param_to_value.get(name, "")
    lines_out: list[str] = []
    for one_based in range(1, TOTAL_LINES + 1):
        if one_based == 1:
            lines_out.append("generated by table_to_params")
        elif one_based in value_line_set:
            lines_out.append(values_by_line.get(one_based, ""))
        else:
            lines_out.append("")
    return lines_out


def main() -> None:
    default_in = Path("params_ver2_table.in")
    default_out = Path("params_ver2.in")
    if len(sys.argv) == 1:
        table_file = default_in
        params_file = default_out
    elif len(sys.argv) == 2:
        table_file = Path(sys.argv[1])
        params_file = default_out
    else:
        table_file = Path(sys.argv[1])
        params_file = Path(sys.argv[2])

    if not table_file.is_file():
        print(f"ERROR: Table file not found: {table_file}", file=sys.stderr)
        sys.exit(1)

    param_to_value = parse_table(table_file)
    missing = [n for n in PARAM_NAMES if n not in param_to_value]
    if missing:
        print(f"ERROR: Missing parameters in table: {missing}", file=sys.stderr)
        sys.exit(1)

    lines_out = build_params_lines(param_to_value)
    params_file.write_text("\n".join(lines_out) + "\n")
    print(f"Wrote {params_file}")


if __name__ == "__main__":
    main()
